/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package schoolmanagement;

import java.util.*;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.text.MessageFormat;
import java.sql.ResultSetMetaData;

/**
 *
 * @author YIBO
 */
public class AdminAct extends javax.swing.JFrame {

    /**
     * Creates new form AdminAct
     */
    
    private static final String username = "root";
    private static final String password = "";
    private static final String dataConn = "jdbc:mysql://localhost:3306/schoolmanagement";
    
    Connection conn;
    PreparedStatement pst;
    ResultSet rs;
    private Object RecordTable;
    
    public AdminAct() {
        initComponents();
        updateDB();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    
    public void updateDB(){
        
        int q, i;
        
        try{
            Class.forName("com.mysql.jdbc.Driver");
            conn = DriverManager.getConnection(dataConn,username, password);
            pst = conn.prepareStatement("select * from teacher");
            
            rs = pst.executeQuery();
            ResultSetMetaData StData = rs.getMetaData();
            
            q = StData.getColumnCount();
            DefaultTableModel RecordTable = (DefaultTableModel)jTable1.getModel();
            RecordTable.setRowCount(0);
            
            
            while(rs.next()){
                
                Vector columnData = new Vector();
                
                for (i=1; i<=q; i++){
                    columnData.add(rs.getString("id"));
                    columnData.add(rs.getString("staffID"));
                    columnData.add(rs.getString("firstname"));
                    columnData.add(rs.getString("lastname"));
                    columnData.add(rs.getString("username"));
                    columnData.add(rs.getString("address"));
                    columnData.add(rs.getString("class"));
                    columnData.add(rs.getString("age"));
                    columnData.add(rs.getString("gender"));
                }
                    RecordTable.addRow(columnData);
                
                
            }
            
            
        }
        catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        } 
    }
    
    
    
    
    
    
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        txtClass = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtstudID = new javax.swing.JTextField();
        txtFname = new javax.swing.JTextField();
        txtLname = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtUname = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtAddy = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtAge = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtGender = new javax.swing.JComboBox<>();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        btnAdd = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnPrint = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel1.setText("Staff Database Management Sysytem");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1270, 60));

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1236, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 56, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1240, 60));

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(95, 158, 160), 4));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtClass.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtClass.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PRI 1", "PRI 2", "PRI 3", "PRI 4", "PRI 5", "PRI 6" }));
        jPanel4.add(txtClass, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 310, 250, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Staff ID");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Firstname");
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("Lastname");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        txtstudID.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtstudID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtstudIDActionPerformed(evt);
            }
        });
        jPanel4.add(txtstudID, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 250, -1));

        txtFname.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jPanel4.add(txtFname, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 250, -1));

        txtLname.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jPanel4.add(txtLname, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 250, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText("Class");
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, -1, -1));

        txtUname.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jPanel4.add(txtUname, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 250, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setText("Address");
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setText("Username");
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, -1));

        txtAddy.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jPanel4.add(txtAddy, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 250, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setText("Gender");
        jPanel4.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, -1, -1));

        txtAge.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jPanel4.add(txtAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 250, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel14.setText("Age");
        jPanel4.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));

        txtGender.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Female", "Male" }));
        jPanel4.add(txtGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, 250, -1));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 390, 470));

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(95, 158, 160), 4));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Staff ID", "Firstname", "Lastname", "Username", "Address", "Class", "Age", "Gender"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel5.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 800, 440));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 10, 830, 470));

        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(95, 158, 160), 4));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAdd.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        btnAdd.setText("Add Staff");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        jPanel6.add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 230, -1));

        btnExit.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        jPanel6.add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 20, 130, -1));

        btnDelete.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        jPanel6.add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 20, 150, -1));

        btnReset.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });
        jPanel6.add(btnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 20, 130, -1));

        btnUpdate.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        jPanel6.add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 20, 170, -1));

        btnPrint.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        btnPrint.setText("Print");
        btnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintActionPerformed(evt);
            }
        });
        jPanel6.add(btnPrint, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, 130, -1));

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 490, 1240, 100));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 1270, 610));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        DefaultTableModel RecordTable =(DefaultTableModel)jTable1.getModel();
        int SelectedRows = jTable1.getSelectedRow();
        try{
            
            
            
            Class.forName("com.mysql.jdbc.Driver");
            conn = DriverManager.getConnection(dataConn,username, password);
            pst = conn.prepareStatement("insert into teacher  (staffID,firstname,lastname,username,address,class,age,gender,password) values "
                    +"(?,?,?,?,?,?,?,?,?)" );
            
            pst.setString(1,txtstudID.getText());
            pst.setString(2,txtFname.getText());
            pst.setString(3,txtLname.getText());
            pst.setString(4,txtUname.getText());
            pst.setString(5,txtAddy.getText());
            pst.setString(6,(String)txtClass.getSelectedItem());
            pst.setString(7,txtAge.getText());
            pst.setString(8,(String)txtGender.getSelectedItem());
            pst.setString(9,txtFname.getText());
           
            
            
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "Staff record updated!");
            updateDB();
        }
        catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminAct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            java.util.logging.Logger.getLogger(AdminAct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        
        DefaultTableModel RecordTable =(DefaultTableModel)jTable1.getModel();
        int SelectedRows = jTable1.getSelectedRow();
        
        try{
            
            int id = Integer.parseInt(RecordTable.getValueAt(SelectedRows,0).toString());
            
            Class.forName("com.mysql.jdbc.Driver");
            conn = DriverManager.getConnection(dataConn,username, password);
            pst = conn.prepareStatement("update teacher set staffID=?,firstname =?,lastname =?,username =?,address =?,class=?,age=? where id =?");
            
            pst.setString(1,txtstudID.getText());
            pst.setString(2,txtFname.getText());
            pst.setString(3,txtLname.getText());
            pst.setString(4,txtUname.getText());
            pst.setString(5,txtAddy.getText());
            pst.setString(6,(String)txtClass.getSelectedItem());
            pst.setString(7,txtAge.getText());
            pst.setString(8,(String)txtGender.getSelectedItem());
           
            pst.setInt(9, id);
            
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "Staff added!");
            updateDB();
        }
        catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminAct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            System.err.println(ex);
        }
        
    }//GEN-LAST:event_btnUpdateActionPerformed
private JFrame frame;
    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        frame = new JFrame ("Exit");
        
        if(JOptionPane.showConfirmDialog(frame,"Confirm if you"," want to exit.", 
                JOptionPane.YES_NO_OPTION)== JOptionPane.YES_NO_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_btnExitActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        DefaultTableModel RecordTable =(DefaultTableModel)jTable1.getModel();
        int SelectedRows = jTable1.getSelectedRow();
        
        
        txtstudID.setText(RecordTable.getValueAt(SelectedRows, 1).toString());
        txtFname.setText(RecordTable.getValueAt(SelectedRows, 2).toString());
        txtLname.setText(RecordTable.getValueAt(SelectedRows, 3).toString());
        txtUname.setText(RecordTable.getValueAt(SelectedRows, 4).toString());
        txtAddy.setText(RecordTable.getValueAt(SelectedRows, 5).toString());
        txtClass.setSelectedItem(RecordTable.getValueAt(SelectedRows, 6).toString());
        txtAge.setText(RecordTable.getValueAt(SelectedRows, 7).toString());
        txtGender.setSelectedItem(RecordTable.getValueAt(SelectedRows, 8).toString());
        
    }//GEN-LAST:event_jTable1MouseClicked

    private void txtstudIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtstudIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtstudIDActionPerformed

    private void btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintActionPerformed
        // TODO add your handling code here:
        
        MessageFormat header = new MessageFormat("Printing in progress");
        MessageFormat footer = new MessageFormat("Page{0, number,integer}");
        
        try{
            jTable1.print(JTable.PrintMode.NORMAL,header,footer);
        }
        catch(java.awt.print.PrinterException e)
        {
            System.err.format("No printer found", e.getMessage());
        }
        
    }//GEN-LAST:event_btnPrintActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        
           txtstudID.setText("");
           txtFname.setText("");
           txtLname.setText("");
           txtUname.setText("");
           txtAddy.setText("");
           txtClass.setSelectedItem("");
           txtAge.setText("");
           txtGender.setSelectedItem("");
          
        
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        
        DefaultTableModel RecordTable =(DefaultTableModel)jTable1.getModel();
        int SelectedRows = jTable1.getSelectedRow();
        
        try{
            
            int id = Integer.parseInt(RecordTable.getValueAt(SelectedRows,0).toString());
            int deleteItem = JOptionPane.showConfirmDialog(null,"Confirm if you want to delete staff.", 
                    "Warning",JOptionPane.YES_NO_OPTION);
                    
                    if (deleteItem ==JOptionPane.YES_OPTION){
            
            Class.forName("com.mysql.jdbc.Driver");
            conn = DriverManager.getConnection(dataConn,username, password);
            pst = conn.prepareStatement("delete from teacher where  id =?");
            
            
            pst.setInt(1, id);
             pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "Staff deleted");
            updateDB();
            
            
           txtstudID.setText("");
           txtstudID.requestFocus();
           txtFname.setText("");
           txtLname.setText("");
           txtUname.setText("");
           txtAddy.setText("");
           txtClass.setSelectedItem("");
           txtAge.setText("");
           txtGender.setSelectedItem("");
           
        }   
           
        }
        
        catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminAct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            System.err.println(ex);
        }
        
    }//GEN-LAST:event_btnDeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminAct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminAct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminAct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminAct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminAct().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnPrint;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtAddy;
    private javax.swing.JTextField txtAge;
    private javax.swing.JComboBox<String> txtClass;
    private javax.swing.JTextField txtFname;
    private javax.swing.JComboBox<String> txtGender;
    private javax.swing.JTextField txtLname;
    private javax.swing.JTextField txtUname;
    private javax.swing.JTextField txtstudID;
    // End of variables declaration//GEN-END:variables
}
