/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package schoolmanagement;

import java.util.*;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.text.MessageFormat;
import java.sql.ResultSetMetaData;

/**
 *
 * @author YIBO
 */
public class AdminAct2 extends javax.swing.JFrame {

    /**
     * Creates new form AdminAct
     */
    
    private static final String username = "root";
    private static final String password = "";
    private static final String dataConn = "jdbc:mysql://localhost:3306/schoolmanagement";
    
    Connection conn;
    PreparedStatement pst;
    ResultSet rs;
    private Object RecordTable;
    
    public AdminAct2() {
        initComponents();
        updateDB();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    
    public void updateDB(){
        
        int q, i;
        
        try{
            Class.forName("com.mysql.jdbc.Driver");
            conn = DriverManager.getConnection(dataConn,username, password);
            pst = conn.prepareStatement("select * from student");
            
            rs = pst.executeQuery();
            ResultSetMetaData StData = rs.getMetaData();
            
            q = StData.getColumnCount();
            DefaultTableModel RecordTable = (DefaultTableModel)jTable1.getModel();
            RecordTable.setRowCount(0);
            
            
            while(rs.next()){
                
                Vector columnData = new Vector();
                
                for (i=1; i<=q; i++){
                 
                    columnData.add(rs.getString("studentID"));
                    columnData.add(rs.getString("fname"));
                    columnData.add(rs.getString("lname"));
                    columnData.add(rs.getString("uname"));
                    columnData.add(rs.getString("address"));
                    columnData.add(rs.getString("class"));
                    columnData.add(rs.getString("age"));
                    columnData.add(rs.getString("gender"));
                    columnData.add(rs.getString("math"));
                    columnData.add(rs.getString("eng"));
                    columnData.add(rs.getString("sci"));
                    columnData.add(rs.getString("cac"));
                    columnData.add(rs.getString("cs"));
                    columnData.add(rs.getString("vr"));
                    columnData.add(rs.getString("quant"));
                    
                }    
                    RecordTable.addRow(columnData);
                
            }
            
            
        }
        catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        } 
    }
    
    
    
    
    
    
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(1400, 0), new java.awt.Dimension(1400, 0), new java.awt.Dimension(1400, 32767));
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        scrollPane1 = new java.awt.ScrollPane();
        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        txtClass = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtstudID = new javax.swing.JTextField();
        txtFname = new javax.swing.JTextField();
        txtLname = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtUname = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        gMath = new javax.swing.JTextField();
        gEng = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        gScience = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        gCAC = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        gCS = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        gVR = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        gQ = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtAddy = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtAge = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtGender = new javax.swing.JComboBox<>();
        jScrollBar1 = new javax.swing.JScrollBar();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        btnAdd = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnPrint = new javax.swing.JButton();
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 30), new java.awt.Dimension(0, 30), new java.awt.Dimension(32767, 30));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel1.setText("Student Database Management Sysytem");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, -1, -1));
        jPanel2.add(scrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1400, 60));

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1396, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 56, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1400, 60));

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(95, 158, 160), 4));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtClass.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtClass.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PRI 1", "PRI 2", "PRI 3", "PRI 4", "PRI 5", "PRI 6" }));
        jPanel4.add(txtClass, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 210, 90, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Student ID");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Firstname");
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Lastname");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        txtstudID.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtstudID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtstudIDActionPerformed(evt);
            }
        });
        jPanel4.add(txtstudID, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 250, -1));

        txtFname.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel4.add(txtFname, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 250, -1));

        txtLname.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel4.add(txtLname, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 250, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Class");
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 210, -1, -1));

        txtUname.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel4.add(txtUname, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 100, -1));

        jPanel8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jPanel8.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, 80, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setText("Mathematics");
        jPanel8.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setText("English Language");
        jPanel8.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        gMath.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        gMath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gMathActionPerformed(evt);
            }
        });
        jPanel8.add(gMath, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, 180, -1));

        gEng.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        gEng.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gEngActionPerformed(evt);
            }
        });
        jPanel8.add(gEng, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, 180, -1));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel18.setText("Science");
        jPanel8.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        gScience.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel8.add(gScience, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, 180, -1));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel19.setText("CAC");
        jPanel8.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        gCAC.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        gCAC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gCACActionPerformed(evt);
            }
        });
        jPanel8.add(gCAC, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, 180, -1));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel20.setText("Computer Science");
        jPanel8.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        gCS.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel8.add(gCS, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, 180, -1));

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel21.setText("Verbal Reasoning");
        jPanel8.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

        gVR.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel8.add(gVR, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, 180, -1));

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel22.setText("Quantitative ");
        jPanel8.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));

        gQ.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel8.add(gQ, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 250, 180, -1));

        jPanel4.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 370, 300));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Address");
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("Username");
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, -1));

        txtAddy.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel4.add(txtAddy, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 250, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setText("Gender");
        jPanel4.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        txtAge.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel4.add(txtAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 170, 90, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setText("Age");
        jPanel4.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 170, -1, -1));

        txtGender.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Female", "Male" }));
        jPanel4.add(txtGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 110, -1));
        jPanel4.add(jScrollBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 10, 710));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 390, 570));

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(95, 158, 160), 4));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "StudentID", "Firstname", "Lastname", "Username", "Address", "Class", "Age", "Gender", "Mathematics", "English Language", "Science", "CAC", "Computer Science", "Verbal Reasoning", "Quantitative"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel5.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 980, 550));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 10, 1000, 570));

        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(95, 158, 160), 4));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAdd.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnAdd.setText("Add Student");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        jPanel6.add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, 230, -1));

        btnExit.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        jPanel6.add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 20, 130, -1));

        btnDelete.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        jPanel6.add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 20, 150, -1));

        btnReset.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });
        jPanel6.add(btnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 20, 130, -1));

        btnUpdate.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        jPanel6.add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 20, 170, -1));

        btnPrint.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnPrint.setText("Print");
        btnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintActionPerformed(evt);
            }
        });
        jPanel6.add(btnPrint, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 20, 130, -1));

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 590, 1420, 60));
        jPanel1.add(filler4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 620, -1, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 1410, 720));
        getContentPane().add(filler3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1420, 230, 10, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        DefaultTableModel RecordTable =(DefaultTableModel)jTable1.getModel();
        int SelectedRows = jTable1.getSelectedRow();
        try{
            
            
            Class.forName("com.mysql.jdbc.Driver");
            conn = DriverManager.getConnection(dataConn,username, password);
            pst = conn.prepareStatement("insert into student(studentID,fname,lname,uname,address,class,age,gender,"
                    +"math,eng,sci,cac,cs,vr,quant,password) values "
                    +"(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)");
            
            pst.setString(1,txtstudID.getText());
            pst.setString(2,txtFname.getText());
            pst.setString(3,txtLname.getText());
            pst.setString(4,txtUname.getText());
            pst.setString(5,txtAddy.getText());
            pst.setString(6,(String)txtClass.getSelectedItem());
            pst.setString(7,txtAge.getText());
            pst.setString(8,(String)txtGender.getSelectedItem());
            pst.setString(9,gMath.getText());
            pst.setString(10,gEng.getText());
            pst.setString(11,gScience.getText());
            pst.setString(12,gCAC.getText());
            pst.setString(13,gCS.getText());
            pst.setString(14,gVR.getText());
            pst.setString(15,gQ.getText());
            pst.setString(16,txtFname.getText());
            
            
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "Student record updated!");
            updateDB();
        }
        catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminAct2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            java.util.logging.Logger.getLogger(AdminAct2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        
        DefaultTableModel RecordTable =(DefaultTableModel)jTable1.getModel();
        int SelectedRows = jTable1.getSelectedRow();
        
        try{
            
            int id = Integer.parseInt(RecordTable.getValueAt(SelectedRows,0).toString());
            
            Class.forName("com.mysql.jdbc.Driver");
            conn = DriverManager.getConnection(dataConn,username, password);
            pst = conn.prepareStatement("update student set studentID=?,fname =?,lname =?,uname =?,address =?,class=?,age=?,"
                    + "gender=?,math=?,eng=?,sci=?,cac=?,cs=?,vr=?,quant=? where id =?");
            
            pst.setString(1,txtstudID.getText());
            pst.setString(2,txtFname.getText());
            pst.setString(3,txtLname.getText());
            pst.setString(4,txtUname.getText());
            pst.setString(5,txtAddy.getText());
            pst.setString(6,(String)txtClass.getSelectedItem());
            pst.setString(7,txtAge.getText());
            pst.setString(8,(String)txtGender.getSelectedItem());
            pst.setString(9,gMath.getText());
            pst.setString(10,gEng.getText());
            pst.setString(11,gScience.getText());
            pst.setString(12,gCAC.getText());
            pst.setString(13,gCS.getText());
            pst.setString(14,gVR.getText());
            pst.setString(15,gQ.getText());
            pst.setInt(16, id);
            
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "Student added!");
            updateDB();
        }
        catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminAct2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            System.err.println(ex);
        }
        
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void gCACActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gCACActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gCACActionPerformed
private JFrame frame;
    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        frame = new JFrame ("Exit");
        
        if(JOptionPane.showConfirmDialog(frame,"Confirm if you"," want to exit.", 
                JOptionPane.YES_NO_OPTION)== JOptionPane.YES_NO_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_btnExitActionPerformed

    private void gMathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gMathActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gMathActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        DefaultTableModel RecordTable =(DefaultTableModel)jTable1.getModel();
        int SelectedRows = jTable1.getSelectedRow();
        
        
        txtstudID.setText(RecordTable.getValueAt(SelectedRows, 1).toString());
        txtFname.setText(RecordTable.getValueAt(SelectedRows, 2).toString());
        txtLname.setText(RecordTable.getValueAt(SelectedRows, 3).toString());
        txtUname.setText(RecordTable.getValueAt(SelectedRows, 4).toString());
        txtAddy.setText(RecordTable.getValueAt(SelectedRows, 5).toString());
        txtClass.setSelectedItem(RecordTable.getValueAt(SelectedRows, 6).toString());
        txtAge.setText(RecordTable.getValueAt(SelectedRows, 7).toString());
        txtGender.setSelectedItem(RecordTable.getValueAt(SelectedRows, 8).toString());
        gMath.setText(RecordTable.getValueAt(SelectedRows, 9).toString());
        gEng.setText(RecordTable.getValueAt(SelectedRows, 10).toString());
        gScience.setText(RecordTable.getValueAt(SelectedRows, 11).toString());
        gCAC.setText(RecordTable.getValueAt(SelectedRows, 12).toString());
        gCS.setText(RecordTable.getValueAt(SelectedRows, 13).toString());
        gVR.setText(RecordTable.getValueAt(SelectedRows, 14).toString());
        gQ.setText(RecordTable.getValueAt(SelectedRows, 15).toString());
    }//GEN-LAST:event_jTable1MouseClicked

    private void gEngActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gEngActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gEngActionPerformed

    private void txtstudIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtstudIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtstudIDActionPerformed

    private void btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintActionPerformed
        // TODO add your handling code here:
        
        MessageFormat header = new MessageFormat("Printing in progress");
        MessageFormat footer = new MessageFormat("Page{0, number,integer}");
        
        try{
            jTable1.print(JTable.PrintMode.NORMAL,header,footer);
        }
        catch(java.awt.print.PrinterException e)
        {
            System.err.format("No printer found", e.getMessage());
        }
        
    }//GEN-LAST:event_btnPrintActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        
           txtstudID.setText("");
           txtFname.setText("");
           txtLname.setText("");
           txtUname.setText("");
           txtAddy.setText("");
           txtClass.setSelectedItem("");
           txtAge.setText("");
           txtGender.setSelectedItem("");
           gMath.setText("");
           gEng.setText("");
           gScience.setText("");
           gCAC.setText("");
           gCS.setText("");
           gVR.setText("");
           gQ.setText("");
        
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        
        DefaultTableModel RecordTable =(DefaultTableModel)jTable1.getModel();
        int SelectedRows = jTable1.getSelectedRow();
        
        try{
            
            int id = Integer.parseInt(RecordTable.getValueAt(SelectedRows,0).toString());
            int deleteItem = JOptionPane.showConfirmDialog(null,"Confirm if you want to delete student.", 
                    "Warning",JOptionPane.YES_NO_OPTION);
                    
                    if (deleteItem ==JOptionPane.YES_OPTION){
            
            Class.forName("com.mysql.jdbc.Driver");
            conn = DriverManager.getConnection(dataConn,username, password);
            pst = conn.prepareStatement("delete from student where  id =?");
            
            
            pst.setInt(1, id);
             pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "Student deleted");
            updateDB();
            
            
           txtstudID.setText("");
           txtstudID.requestFocus();
           txtFname.setText("");
           txtLname.setText("");
           txtUname.setText("");
           txtAddy.setText("");
           txtClass.setSelectedItem("");
           txtAge.setText("");
           txtGender.setSelectedItem("");
           gMath.setText("");
           gEng.setText("");
           gScience.setText("");
           gCAC.setText("");
           gCS.setText("");
           gVR.setText("");
           gQ.setText("");
        }   
           
        }
        
        catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminAct2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            System.err.println(ex);
        }
        
    }//GEN-LAST:event_btnDeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminAct2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminAct2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminAct2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminAct2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminAct2().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnPrint;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnUpdate;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler3;
    private javax.swing.Box.Filler filler4;
    private javax.swing.JTextField gCAC;
    private javax.swing.JTextField gCS;
    private javax.swing.JTextField gEng;
    private javax.swing.JTextField gMath;
    private javax.swing.JTextField gQ;
    private javax.swing.JTextField gScience;
    private javax.swing.JTextField gVR;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private java.awt.ScrollPane scrollPane1;
    private javax.swing.JTextField txtAddy;
    private javax.swing.JTextField txtAge;
    private javax.swing.JComboBox<String> txtClass;
    private javax.swing.JTextField txtFname;
    private javax.swing.JComboBox<String> txtGender;
    private javax.swing.JTextField txtLname;
    private javax.swing.JTextField txtUname;
    private javax.swing.JTextField txtstudID;
    // End of variables declaration//GEN-END:variables
}
